#!/bin/sh
# File to run the blackscholes benchmark
cd $home/18742/parsec-3.0/pkgs/apps/blackscholes/inst/amd64-linux.gcc/bin/
/sbin/m5 dumpresetstats
./blackscholes 1 in_4K.txt prices.txt
echo "Done :D"
/sbin/m5 exit
