#!/bin/sh
# File to run the dedup benchmark
cd $home/18742/parsec-3.0/pkgs/apps/dedup/inst/amd64-linux.ret/bin/
/sbin/m5 dumpresetstats
./dedup -c -p -v -t 1 -i media.dat -o output.dat.ddp
echo "Done :D"
/sbin/m5 exit
