#!/bin/sh
# File to run the ferret benchmark
cd $home/18742/parsec-3.0/pkgs/apps/ferret/inst/amd64-linux.gcc/bin/
/sbin/m5 dumpresetstats
./ferret corel lsh queries 10 20 1 output.txt
echo "Done :D"
/sbin/m5 exit
