#!/bin/sh
# File to run the fluidanimate benchmark
cd $home/18742/parsec-3.0/pkgs/apps/fluidanimate/inst/amd64-linux.ret/bin/
/sbin/m5 dumpresetstats
./fluidanimate 1 5 in_35K.fluid out.fluid
echo "Done :D"
/sbin/m5 exit
