#!/bin/sh
# File to run the freqmine benchmark
cd $home/18742/parsec-3.0/pkgs/apps/freqmine/inst/amd64-linux.gcc/bin/
/sbin/m5 dumpresetstats
export OMP_NUM_THREADS=1
./freqmine kosarak_250k.dat 220
echo "Done :D"
/sbin/m5 exit
