#!/bin/sh
# File to run the streamcluster benchmark
cd $home/18742/parsec-3.0/pkgs/apps/streamcluster/inst/amd64-linux.ret/bin/
/sbin/m5 dumpresetstats
./streamcluster 10 20 32 4096 4096 1000 none output.txt 1
echo "Done :D"
/sbin/m5 exit
