#!/bin/sh
# File to run the swaptions benchmark
cd $home/18742/parsec-3.0/pkgs/apps/swaptions/inst/amd64-linux.gcc/bin/
/sbin/m5 dumpresetstats
./swaptions -ns 16 -sm 10000 -nt 1
echo "Done :D"
/sbin/m5 exit
