#!/bin/sh
# File to run the x264 benchmark
cd $home/18742/parsec-3.0/pkgs/apps/x264/inst/amd64-linux.gcc/bin/
/sbin/m5 dumpresetstats
./x264 --quiet -qp 20 --partitions b8x8,i4x4 --ref 5 --direct auto --b-pyramid --weightb --mixed-refs --no-fast-pskip -me umh --subme 7 --analyse b8x8,i4x4 --threads 1 -o eledream.264 eledream_640x360_8.y4m
echo "Done :D"
/sbin/m5 exit
